export { SupervisorDashboardScreen } from './screens/SupervisorDashboardScreen'
export { DashboardScreen } from './screens/DashboardScreen'
export { TrabajadoresCrudScreen } from './screens/TrabajadoresCrudScreen'
export { AsistenciaScreen } from './screens/AsistenciaScreen'
export { TrasladosScreen } from './screens/TrasladosScreen'
export { ConfiguracionScreen as SupervisorConfiguracionScreen } from './screens/ConfiguracionScreen'
