export { AdminDashboardScreen } from './screens/AdminDashboardScreen'
export { FincaDashboardScreen } from './screens/FincaDashboardScreen'
export { FincasCrudScreen } from './screens/FincasCrudScreen'
export { TrabajadoresPorFincaScreen } from './screens/TrabajadoresPorFincaScreen'
export { SalariosScreen } from './screens/SalariosScreen'
export { PlanillaScreen } from './screens/PlanillaScreen'
export { AsistenciaPorFincaScreen } from './screens/AsistenciaPorFincaScreen'
export { TrasladosAdminScreen } from './screens/TrasladosAdminScreen'
export { SupervisoresCrudScreen } from './screens/SupervisoresCrudScreen'
export { ConfiguracionScreen as AdminConfiguracionScreen } from './screens/ConfiguracionScreen'
